site_name: My Docs
theme:
    name: 'material'
    # サイトの言語設定
    language: ja

extra:
    # Materialデザインのアイコン拡張
    logo:
        icon: 'developer_board'

markdown_extensions:
    - admonition # アラート修飾の設定
    - pymdownx.details # コンテンツの折りたたみ
    - pymdownx.keys
    - def_list
    - pymdownx.mark
    - pymdownx.emoji
    - fontawesome_markdown
    - pymdownx.superfences # スーパーフェンス機能の設定
    # コードハイライトの設定
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true
    # PlantUMLの表示設定
    - plantuml_markdown:
        server: http://www.plantuml.com/plantuml